name: Bug Report
description: Report a bug for a core plugin, the desktop client, or the website!
title: 'Bug Report: '
labels:
  - Bug
body:
  - type: dropdown
    id: category
    attributes:
      label: Is this a client, plugin, or website bug?
      description: Please select the "product" that you are experiencing the bug on!
      options:
        - Client
        - Plugin
        - Website
    validations:
      required: true
  - type: checkboxes
    id: verified-nondupe
    attributes:
      label: I verified this is not a duplicate report
      description: >-
        We ask that you check to veirfy this is not a duplicate bug here:
        https://github.com/Highl1te/HighliteDesktop/issues
      options:
        - label: 'Yes'
          required: true
  - type: checkboxes
    id: verify-highlite-bug
    attributes:
      label: I verified this bug only occurs with HighLite
      description: >-
        If it is a HighLite client bug we ask that you check to make sure it is
        actually HighLite and not just a High Spell web client issue.
      options:
        - label: 'Yes'
          required: false
        - label: Not Applicable
          required: false
    - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: >-
        Please provide details of what happens when the bug occurs, aka the
        problematic behavior. Pictures, textual descriptions, etc. are all
        appreciated.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: >-
        Please describe how this bug can be reproduced. A step-by-step text
        description, a video, or screenshots are all appreciated.
      validations:
        required: true
