name: Suggestion
description: >-
  Request a core plugin, desktop client feature/enhancement, or a website
  feature/enhancement
title: 'Suggestion: '
labels:
  - Feature
body:
  - type: dropdown
    id: category
    attributes:
      label: Is this a client, plugin, or website suggestion?
      description: Please select the "product" that you are creating a suggestion for!
      options:
        - Client
        - Plugin
        - Website
    validations:
      required: true
  - type: checkboxes
    id: verify-non-duplicate
    attributes:
      label: I verified this is not a duplicate suggestion
      description: >-
        We ask that you verify that this suggestion is not a duplicate of
        another found here: https://github.com/Highl1te/HighliteDesktop/issues
      options:
        - label: 'Yes'
          required: true
  - type: textarea
    id: suggestion-description
    attributes:
      label: Suggestion
      description: >-
        Please provide a solid description of the feature you would like to see
        implemented! Screenshots, examples, etc. are all welcome.
    validations:
      required: true
